[zh]
    contentDir = 'content/zh'
    disabled = false
    languageCode = 'zh-CN'
    languageDirection = 'ltr'
    languageName = '简体中文'
    weight = 1
    [zh.pagination]
        disableAliases = false
        pagerSize = 12
        path = 'page'
    [zh.taxonomies]
        author = 'author'
        category = 'categories'
        series = 'series'
        tag = 'tags'

[en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 2
    [en.pagination]
        disableAliases = false
        pagerSize = 12
        path = 'page'
    [en.taxonomies]
        author = 'author'
        category = 'categories'
        series = 'series'
        tag = 'tags'

